### ISSUE TITLE
Using Promises

### ISSUE THREAD

**Issue by dajinchu** [ryan-bradford/WHAM#11]
In a lot of the code where we interact with the MySQL database we have long nested chains of callbacks, especially in cases where we have to query the database repeatedly. JavaScript has something called Promises that can make callback code significantly easier to work with. 

[This quick read explains it better than I ever could](http://bluebirdjs.com/docs/why-promises.html)
I would add that promises not only make code cleaner, they also add real new functionality with functions like `Promise.all`

Bluebird is a specific library for Promises, though NodeJS comes with it's own Promise library, so it is not necessary to use bluebird. [However, this library wraps the mysql library to use bluebird promises.](https://github.com/lukeb-uk/node-promise-mysql)

We could consider using the above library to make our database code a lot easier to work with, although it will require learning Promises thoroughly. We will also need to make sure that the mysql library has all the features we need, as it isn't maintained that actively. There may be other ways to use promises with mysql such as [using the `bluebird.promisifyAll()` helper](https://smalldata.tech/blog/2018/03/20/node-js-mysql-connection-pool-async-await)

**Comment by ryan-bradford** [comment]
Huh those sound really cool, almost magical. I talked to Prof. Lerner a little while back and he told me about arrow functions (they make dealing with scope of callbacks in ES6 classes easier), so now I wanna try using Promises and Arrow Functions to clean up the code. 

Based on what you linked, the DB code could go from super shitty to kinda nice!

**Comment by ryan-bradford** [comment]
Just finished using the promises to rewrite the DB code. It's looking good. There are still a few methods where things are weird, but overall it looks better! Tell me what you think.

**Comment by dajinchu** [comment]
Wow this is very neat, nicely done!

Two things I can think of:

1. I think we can actually promise-ify our actual DB functions themselves too. Instead of taking a callback, and calling it in the final .then() of our database-calling promises, we simply _return the promise itself._ Then, in the /main code, we can work with the database helpers as promises too!
2. `Promise.all` to send multiple DB queries, instead of chaining `.then` This will execute all queries at the same time, and resolve once all queries finish, returning the result of all queries, which we can then process and return.

I did both of those things with get_patient_info, and put it in a new branch. Here's a link to the commit:
https://github.com/ryan-bradford/WHAM/commit/b108c51dc2f5230b9a98ce4a32f2083213497d72

Let me know if you think this is a better or worse way of doing things.

**Comment by ryan-bradford** [comment]
Ahhh that's real creative. I didn't know about Promises.all, and returning the promise itself to make the function a promise is really cool. Also, moving the catch clause to the /main JS files makes the code much more readable. I'll merge this with the master branch (and do it to the rest of the code) sometimes tomorrow!

**Comment by ryan-bradford** [comment]
So I switched it to using Promises rather than callbacks minus one tricky function (get_all_patients)! Its looking good. I'm gonna remove your branch now that its in the real code.
