### ISSUE TITLE
Logging in queries the patientDB, then the therapistDB

### ISSUE THREAD

**Issue by dajinchu** [ryan-bradford/WHAM#3]
We should somehow separate logging in for patients and therapist. I think we could:

1. Have two routes, ie. /logintherapist and /loginpatient or something along those lines...
2. Include whether you want to login as therapist or as patient in the request body.

**Comment by dajinchu** [comment]
To add to this, on the HTML side, we gotta have some kind of home page situation where you can go to Register, Login as Patient, and Login as Therapist

**Comment by ryan-bradford** [comment]
I think option one makes more sense. Having the URL denote type feels better. 
I'll make four URLS: 
1. '/login' which allows you to select your user type and redirects you to the proper page. Also, it will allow you to be redirected to the create account page. 
2. '/login/patient' which shows the login page for a patient and you can post to it to login as a patient. 
3. '/login/therapist' which shows the login page for a therapist and you can post to it to login as a therapist. 
4. '/register' which shows the create an account page. (It does not have any POST functionality). 

I'm gonna code this up right now, but if you have a different idea feel free to say.

**Comment by dajinchu** [comment]
Yeah sounds good. Would the register page  have to post to /therapist and /patient depending on what the user wants?

**Comment by ryan-bradford** [comment]
Yea, the way it's set up right now it would have to.
