### ISSUE TITLE
Weird MySQL bug

### ISSUE THREAD

**Issue by ryan-bradford** [ryan-bradford/WHAM#5]
I'm getting this odd bug where occasionally when I run the tests (either HTTPTests or PermTests) everything fails and the MySQL database gets corrupted and has to be reinitialized. I'm wondering if this is a my machine thing or if you could replicate it @dajinchu

**Comment by dajinchu** [comment]
Huh I'll try when I get home. Just for consistency, what command are you using for running tests?

**Comment by ryan-bradford** [comment]
I just ran all the tests (node_modules/mocha/bin/mocha) and occasionally the MySQL database just stopped working.

**Comment by ryan-bradford** [comment]
It seems to happen when a lot of tests fail and is probably just a stupid thing going on with my computer. I'm gonna close this issue.
