### ISSUE TITLE
DB socketPath

### ISSUE THREAD

**Issue by dajinchu** [ryan-bradford/WHAM#6]
Is the socketPath argument in the mysql.createPool() neccessary? On my machine mySQL will not connect unless either the socketPath is omitted or is an empty string. I think it is because I'm on Windows. Can we maybe have socketPath read from .env, or remove it? I thought host and port should be enough to connect.

**Comment by ryan-bradford** [comment]
Ahhh sorry that's my bad. When I was trying to solve the MySQL crash bug, I read somewhere on StackOverflow that using socketPath might solve the issue. It ended up not working, and I just forgot to delete that config line. Feel free to remove it!
