### ISSUE TITLE
Patient Accept Therapist Request

### ISSUE THREAD

**Issue by ryan-bradford** [ryan-bradford/WHAM#8]
Right now, when the therapist wants to add a patient all they have to do is type their username, click add, and they have total permission over that patient. We should make it so when the therapists adds a patient, the patient has to accept their request on the web app side.

**Comment by ryan-bradford** [comment]
I roughly did it. There seems to be a strange bug where sometimes a therapists can accept the request for the patient (thus nullifying the whole point of "requests"), and also has permission to view the patients profile before the request is ever accepted. I can't figure out why, and I don't 100% even know if it happens...

**Comment by dajinchu** [comment]
Huh, I'll take a look

**Comment by ryan-bradford** [comment]
I figured it out! The problem was there was permissions stored in the instance of ACL that was passed between sessions of the app during the testing. When HTTPTests ran it mutated a variable that was passes to PermTests (and thus screwed up everything test-wise).
